SiteConfig/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'The Kuks Blog' #login page
admin.site.index_title = 'The Kuks Blog Administration '
admin.site.site_title = 'The Kuks Site'
admin.site.site_index = 'The Kuks Adminstrator'

name = 'The Kuks'

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.homepage, name='homepage'),
	path('create-blog', views.create, name="create-blog"),
	path('blog/<slug:slug>', views.detail, name="detail"),
	path('blog/<slug:slug>/edit', views.edit, name="edit-blog"),
	path('about', views.about, name='about')
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

def upload_location(instance, filename):
	path = 'blog/{}/{}'.format(str(instance.tag), str(filename))
	return path

class tag(models.Model):
	name = models.CharField(max_length=200)
	def __str__(self):
		return str(self.name)
	def get_absolute_url(self):
		return reverse('tag', args=[str(self.name)])
	class Meta:
		verbose_name_plural = "Tags"
		ordering =  ['name', 'id']


class Entry(models.Model):
	image 		= models.ImageField(upload_to=upload_location, blank=True, null=True, default="image/default.png")
	title 		= models.CharField(max_length=250, help_text="Blog title", unique=True)
	body		= models.TextField()
	youtube_src = models.CharField(max_length=200, default='', blank=True)
	tag 		= models.ForeignKey(tag, on_delete=models.CASCADE, related_name="tags", null=True, default=1)
	pub_date 	= models.DateField(auto_now_add=True)
	slug 		= models.SlugField(blank=True, default='')

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		super(Entry, self).save()

	def get_absolute_url(self):
		return reverse('detail', args=[str(self.slug)])

	class Meta:
		verbose_name_plural = "Blog Entry."
		ordering = ['-pub_date','-id']

developer/models.py
from django.db import models

class langauage(models.Model):
	name = models.CharField(max_length=200, unique=True)
	symbol = models.URLField(blank=True, default='')

	def __str__(self):
		return str(self.name)

	class Meta:
		ordering = ['name']

class tool(models.Model):
	name = models.CharField(max_length=200, unique=True,)
	symbol = models.URLField(blank=True, default='')
	def __str__(self):
		return str(self.name)
	class Meta:
		ordering = ['name']

class project(models.Model):
	image 		= models.ImageField(upload_to="projects/", default="project/default.png", blank=True, null=True)
	title 		= models.CharField(max_length=250)
	short_desc 	= models.TextField()
	completed 	= models.BooleanField(default=False)
	def __str__(self):
		return str(self.title)

class programmer(models.Model):
	username 	= models.CharField(max_length=200, unique=True)
	fullname 	= models.CharField(max_length=250)
	short_bio 	= models.TextField()
	dob 		= models.DateField(verbose_name="Date of Birth")
	github 		= models.CharField(max_length=200, help_text="Github username")
	projects 	= models.ManyToManyField(project, help_text="project", blank=True, null=True)
	lang 		= models.ManyToManyField(langauage, blank=True, null=True)
	tools 		= models.ManyToManyField(tool, blank=True, null=True)

	def __str__(self):
		return str(self.username)

blog/forms.py
from django.forms import ModelForm
from . models import Entry


class BlogEntry(ModelForm):

	class Meta:
		model = Entry
		fields = ['image','title','youtube_src','body','tag']


class UpdateBlogForm(ModelForm):

	class Meta:
		model = Entry
		fields = ['image','title','body', 'tag','slug']

blog/views.py
from . models import *
from . forms import BlogEntry, UpdateBlogForm 
from django.shortcuts import render, redirect, get_object_or_404
from .utils import paginateblog
import json
from developer.models import programmer, langauage, tool

def homepage(request):
	blog = []
	custom_range, blog, paginator = paginateblog(request,blog, 5)
	return render(request, 'blog/index.html', context={'blog':blog})

def create(request):
	form = BlogEntry()
	value = tag.objects.all()
	if request.method == 'POST':
		form = BlogEntry(request.POST or None, request.FILES or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			instance = get_object_or_404(Entry, title=str(instance.title))		
			return redirect('detail', instance.slug)
		redirect('create-blog')
	return render(request, 'blog/create-blog.html', context={'CreateBlogForm':form, 'tag':value})

def detail(request, slug):
	blog = get_object_or_404(Entry, slug=slug)
	return render(request, 'blog/detail.html', context={'blog':blog})

def edit(request, slug):
	context = {}
	blog = Entry.objects.get(slug=slug)
	value = tag.objects.all()
	
	if request.POST:
		form = UpdateBlogForm(request.POST or None, request.FILES or None, instance=blog)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			return redirect('detail', slug=instance.slug)

	form = UpdateBlogForm(
		initial = {
				"title"	: blog.title,
				"body"	: blog.body,
				"tag"	: blog.tag,
				"slug"	: blog.slug,
				"image"	: blog.image,
		}

	)

	return render(request, 'blog/edit.html', context={'form':form, 'tag':value})

def about(request):
	user = get_object_or_404(programmer, username="Igwesi")
	lang = langauage.objects.all()
	tools = tool.objects.all() 
	return render(request, 'about.html', context={'user':user, 'lang':lang,'tools':tools})

developer/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/create-blog.html
{% extends 'base.html' %}

{% block title %} | Create Blog {% endblock %}

{% block breadcrumb %}<li class="breadcrumb-item active" aria-current="page">Create Blog</li>{% endblock %}

{% block content %}
<form class="form" method="POST" enctype="multipart">{% csrf_token %}
	<div class="row font-weight-bold d-flex flex-sm-row-reverse">
		<div class="col-4 p-5 p-sm-0">
			<!-- Image -->
			<div class="form-group image-group border border-dark" id="id_image_group" style="height: 400px">
				<label for="id_image" class="btn btn-outline-success mt-3">Image Section</label>
				<img src="" loading="lazy" class="img-fluid" height="450px" id="id_image_display">
				<div class="middle">
					<div class="text">Upload image</div>
				</div>
			</div>
			<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
		</div>
		<div class="col-8">
			<div class="form-group">
				<label for="id_body">Title:</label>
				<input class="form-control" type="text" name="title" maxlength="250" required="" id="id_title" placeholder="Title">
			</div>
			<div class="form-group">
				<label for="id_body">Body:</label>
				<textarea class="form-control" name="body" cols="40" rows="10" required="" id="id_body"></textarea>
			</div>
			<div class="form-group">
				<label for="id_youtube_src">Youtube:</label>
				<input class="form-control" type="text" name="youtube_src" maxlength="200" id="id_youtube_src">
			</div>
			<div class="form-group">
				<label for="id_tag">Tag:</label>
				<select class="form-control" name="tag" id="id_tag">
				{% if tag %}
				{% for i in tag %}
				  <option id="id_option" value="{{ i.id }}" selected>{{ i.name }}</option>
				{% endfor %}
				{% endif %}
				</select>
			</div>
			<input class="btn btn-outline-success" type="submit" name="submit"/>
		</div>
	</div>
	
</form>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'base.html'%}
{% load humanize %}

{% block title %} | {{ blog.title | truncatechars:30 }} {% endblock %}

{% block breadcrumb %}<li class="breadcrumb-item" aria-current="page">blog</li>
<li class="breadcrumb-item" aria-current="page">{{ blog.tag }}</li>
<li class="breadcrumb-item active" aria-current="page">{{ blog.title | truncatechars:30 }}</li>{% endblock %}


{% block content %}
<header class="masthead">
    <div class="overlay"></div>
      <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
              <div class="site-heading" id="site-heading">
                <h1> The Kuks </h1>
              </div>
            </div>
          </div>
      </div>
    </div>
</header>

<hr class="border p-2 border-success bg-success">
<div class="container">
  <div class="row">
    <div class="col-8 jumbotron mx-auto">
      <h2 class="post-title text-black font-weight-bold">{{blog.title}}</h2>
      <p>{{blog.pub_date }}</p>
      {% if blog.image %}
      <img  class="img-fluid" height="200" width="550px" src="{{blog.image.url}}" alt="card image cap">
      {% else %}{% endif %}

      <div class="post-preview">
        <h5 class="post-subtitle">
          {{blog.highlight}}
          <a href="{% url 'edit-blog' blog.slug %}">Edit Post</a>
        </h5><hr>
        {% if blog.youtube_src %}
        <iframe width="650" height="315" src="https://www.youtube.com/embed/{{ blog.youtube_src }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        {% endif %}
       
        <section class="blog-body"> 
          <text class="card-body p-4">{{ blog.body | linebreaks }}</text>
        </section>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/edit.html
{% extends 'base.html' %}

{% block title %} | Create {% endblock %}


{% block breadcrumb %}<li class="breadcrumb-item active" aria-current="page">Edit Blog | <a href="{% url 'detail' form.initial.slug %}">{{ form.initial.title }}</a></li>{% endblock %}

{% block content %}
<form class="form" method="POST" enctype="multipart">{% csrf_token %}{% if success_message %}
	<h3 style="color:green; text-align: center;">{{success_message}}</h3>{% endif %}
	{% for field in form %}
		<p>
			{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
			{% endfor %}
		</p>
	{% endfor %}
	{% if form.non_field_errors %}
		<div style="color: red">
			<p>{{form.non_field_errors}}</p>
		</div>
	{% endif %}
	
	<div class="row">
		<!--Left Column  -->
		<div class="col-4 col-sm-8 mx-auto">
			<!-- Image -->
			<div class="form-group image-group" id="id_image_group">
				<label for="id_image" class="border-0 font-weight-bold">Current Image:<a href="{{form.initial.image.url}}"> {{form.initial.image.url}}</a></label>
				<img src="{{form.initial.image.url}}" loading="lazy" class="img-fluid" height="450px" id="id_image_display">
				<div class="middle">
					<div class="text">Change image</div>
				</div>
			</div>
			<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
		</div>
		<!-- Right Column -->
		<div class="col-8 col-sm-8 mx-auto">
			<!-- Title  -->
			<div class="form-group">
				<label for="id_title" class="h4 font-weight-bold">Title:</label>
				<input class="form-control" type="text" name="title" maxlength="250" required="" id="id_title" value="{{form.initial.title}}">
			</div>
			
			<!-- Body -->
			<div class="form-group">
				<label for="id_body" class="h4 font-weight-bold">Body:</label>
				<textarea class="form-control" name="body" cols="40" rows="10" required="" id="id_body">{{form.initial.body}}</textarea>
			</div>

			<!-- Tag -->
			<div class="form-group">
				<label for="id_tag" class="h4 font-weight-bold">Tag:</label>
				<select class="form-control" name="tag" id="id_tag">
				{% if tag %}
				{% for i in tag %}
				  <option value="{{ i.id }}" {% if blog.tag == i.name %}selected=""{% endif %}>{{ i.name }}</option>
				{% endfor %}
				{% endif %}
				</select>
			</div>
			<!-- Slug -->
			<div class="form-group">
				<label for="id_slug" class="h5 font-weight-bold">slug:</label>
				<input class="form-control" type="text" name="slug" maxlength="200" required="" id="id_slug" value="{{form.initial.slug}}">
			</div>

			<!-- Submit Button -->
			<input class="btn btn-outline-success font-weight-bold" type="submit" name="Update"/>
		</div>
	</div>
</form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html'%}
{% load static %}

{% block  header %}
  {% include "snippets/header.html" %}
{% endblock %}

{% block content %}
  <!-- Main Content -->
  <div class="row mt-5 mx-auto">
    <div class="col-lg-8 col-md-8 col-sm-12">
        {% for post in blog %}
        <div class="card">
          <div class="card-header">
            <h2 class="post-title p-2" style="text-transform:uppercase">
              {{post.title | truncatechars:50}}
            </h2>
            <div class="post-meta mb-2">
              posted
              on <span class="font-weight-bold text-info"> {{post.pub_date}}</span>
            </div>
            <div class="card-img">
              <img class="img-fluid" src="{{post.image.url}}" width="300px" height="200px" loading="lazy">
            </div>  
            </a>
          </div>
          <div class="post-subtitle card-body p-4">
              {{post.body | truncatechars:250}}
              <div class="clearfix">
                <a class=" btn btn-danger float-right" href="{% url 'detail' post.slug %}">Read more &rarr;</a>
              </div>
          </div>
        </div>
        <hr>
        {% endfor %}
        <!-- Pager -->
        <div class="clearfix mt-2">
          <a class=" btn btn-primary float-right" href="{# url 'next' #}">Older blog &rarr;</a>
        </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-12 mx-auto">
      <div class="card">
        <div class="card-header btn btn-outline-warning">Related Blog</div>
        <div class="card-body meta">
          <ul class="list-inline">
            <li><a href="" class="nav-link btn btn-outline-success mb-2">Artificial Intelligence</a></li>
            <li><a href="" class="nav-link btn btn-outline-danger mb-2">Data Science</a></li>
            <li><a href="" class="nav-link btn btn-outline-success mb-2">Python Programming</a></li>
            <li><a href="" class="nav-link btn btn-outline-danger mb-2">Django Framework</a></li>
            <li><a href="" class="nav-link btn btn-outline-success">Javascript</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/snippets/footer.html
<p class="copyright  m-2 text-center text-white">Copyright © Eminent {{now}}</p>

blog/templates/snippets/header.html
{% load static %}
<!-- Page Header -->
  <header class="header mb-4" style="background-image: url('static/wood-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="site-heading">
            <h1>The Kuks Blog</h1>
            <p class="subheading">The most Informative site</p>
          </div>
        </div>
      </div>
    </div>
  </header>

blog/templates/snippets/navbar.html
{% load static %}
    <!-- Navigation -->
      <nav class="navbar navbar-expand navbar-dark fixed-top bg-dark" id="mainNav">
        <div class="container">
          <a class="navbar-brand font-weight-bold" href="{% url 'homepage' %}">The Kuks</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto font-weight-bold">
              <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'create-blog' %}">Create</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <!-- End Navigation -->

blog/templates/snippets/scripts.html
{% load static %}
   <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Custom Javascripts -->
    <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>

blog/templates/snippets/stylesheet.html
{% load static %}
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <!-- Custom stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-8">
			<div class="card p-3">
				<div class="row">
					<div class='h1 font-weight-bold p-2 text-black'>
						{{ user.fullname }}
						<img height="60" width="60" src="https://media1.tenor.com/images/3ca4190df184f2329bb9f0bd06ea0cc2/tenor.gif?itemid=10604183" />
					</div>
					<div class="card-body">
						{{ user.short_bio | linebreaks }}
					</div>
				</div>

				<div class="row mx-auto">
					<div class='h2 font-weight-bold'>Github Stats</div>
					<div class="">
						<a href="https://github.com/{{ user.github }}">
					    <img align="center" alt="{{ user.fullname }} Github Stats" src="https://github-readme-stats.vercel.app/api?username={{ user.github }}&show_icons=true&theme=tokyonight">
						</a>
					</div>
				</div>

				<div class="row mt-5 mx-auto mb-5">
					<div class="h4 font-weight-bold">Languages and Tools: </div>
					<ul class="list-group list-group-numbered">
						<li class="list-group-item">
							{% for i in lang %}
							<img class='m-2' align="left" alt="{{i.name}}" width="40px" src="{{ i.symbol }}"/>
							{% endfor %}
							{% for i in tools %}
							<img class='m-2' align="left" alt="{{i.name}}" width="40px" src="{{ i.symbol }}"/>
							{% endfor %}
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="col-4 mt-4">
			<div class="row card">
				<div align="center">
				  <div class='h4 font-weight-bold'>Top Languages</div>
				  <a href="https://github.com/{{user.github}}">
				    <img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username={{user.github}}&theme=tokyonight&layout=compact">
				  </a>
				</div>
			</div>
			<div class="row card">
				<div align="center">        
				   <div class='h4 font-weight-bold'>Visitor Count</div>
				   <embed src="https://profile-counter.glitch.me/{{user.github}}/count.svg"></embed>
				</div>
				<div align="center">
					<b>❤️ Thank you for visiting my Profile ❤️</b>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" style="height: 100%">
  <head>
  	<meta charset="utf-8">
    <meta name="author" content="Igwesi">
    <meta name="description" content="The Kuks Blog">
    <meta name="mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>The Kuks {% block title %}{% endblock %}</title>
    {% include "trademark.txt" %}
    {% csrf_token %} 
    <meta name="viewport" content="width=device-width, initial-scale=2, shrink-to-fit=no">
    <script src="https://widgets.coingecko.com/coingecko-coin-price-marquee-widget.js"></script>
    {% include "snippets/stylesheet.html" %}
    <link rel="icon" href="{% static 'wood-bg.jpg' %}" sizes="192x192">
    <link rel="apple-touch-icon" href="{% static 'wood-bg.jpg' %}">
  </head>

  <body style="height: 100%">
    <!-- Navbar -->
    <section class="mb-5 bg-dark">{% include "snippets/navbar.html" %}</section>
    <!-- EndNavbar -->
 
    <!-- Breadcrumb -->
    <section class="container mt-5">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <div class="container mt-4">
            <coingecko-coin-price-marquee-widget  coin-ids="bitcoin,ethereum,eos,ripple,litecoin" currency="usd" background-color="#ffffff" locale="en"></coingecko-coin-price-marquee-widget>
          </div>
        </ol>
      </nav>
      <!-- header -->
      {% block header %}{% endblock %}
      <!-- End header -->
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Home</a></li>
          {% block breadcrumb %}{% endblock %}
        </ol>
      </nav>
      <!-- EndBreadcrumb -->
    </section>
 
    <!-- Main Content -->
    <section class="container">
      {% block content %}{% endblock %}
    </section>
    <!-- Main Content -->
    
    <section>
      {% include "snippets/footer.html" %}
    </section>
    {% include "snippets/scripts.html" %}
  </body>
</html>